### ISSUE TITLE
Whatsapp Web via websocket on browserless

### ISSUE THREAD

**Issue by MarStefo** [pedroslopez/whatsapp-web.js#1349]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Previously it was possible to start whatsapp-web.js with puppeteer using a browserless/chrome docker image.

According to this issue https://github.com/pedroslopez/whatsapp-web.js/pull/889 "_For now, Remote Browser / Browserless is not supported._" I ask you if there is a reimplementation of the missing function.

Thank you.

### Describe the solution you'd like.

Put back the functionality to be able to run a browserless docker container.

```js
    const authStrategy = new LocalAuth({
        clientId: metadata.name,
        // dataPath: storage.sessionPath,
    });

    account = new Client({
        puppeteer: {
            headless: false,
            args: ['--no-sandbox'],
            browserWSEndpoint: process.env.BROWSER_URL, // ws://chrome:3000
        },
        authStrategy,
    });
```

**Comment by tryvin** [comment]
@MarStefo I would assume the "issue" is that now the sessions are stored as userData for the headless browser, so, if you use an external browser you wouldn't be able to save userData hence the session

**Comment by MarStefo** [comment]
That's right @tryvin, it's not a real "bug" or "feature". 

All right what you say. I am using Docker to manage the project and I was using a dedicated container for the browser.
For instance:

```yml
# docker-compose.yml
# ...
   image: browserless/chrome:1.22-chrome-stable
```

Can this functionality be reintroduced? Or does this new mode make it impossible to do so?

Cheers

**Comment by pauloboc** [comment]
Hello,

Yes, you can use browserlese.
Use a volume to save the session.

`
volumes:
      - ./.wwebjs_auth/session-client-master/:/usr/src/app/user-data-dir
  `
`
    environment:
      - DEFAULT_USER_DATA_DIR=/usr/src/app/user-data-dir
`

**Comment by MarStefo** [comment]
Thanks! This worked great.
It was easier than expected.

Have a nice day!

**Comment by eslambasher** [comment]
@MarStefo Hello, can u please show me ur docker-compose / exmaple how u set it pls ? i try it but the browser still disconnecting :/

**Comment by MarStefo** [comment]
Hi @eslambasher 

Here's to you:

**docker-compose.yml**
```yml
version: "3.9"
services:
  node:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: "node server.js"
    restart: always
    depends_on:
      - browser
    ports:
      - "8080:8080"
    environment:
      BROWSER_URL: 'ws://browser:3000'
# ...

  browser:
    image: browserless/chrome:1-chrome-stable
    hostname: browser
    volumes:
      - ./.wwebjs_auth/session-master/:/usr/src/app/user-data-dir
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: 'true'
      WORKSPACE_EXPIRE_DAYS: 1
      ENABLE_CORS: 'true'
      CHROME_REFRESH_TIME: 86400000
      DEFAULT_BLOCK_ADS: 'true'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      ENABLE_XVBF: 'true'
      CHROME_PATH: '/usr/bin/google-chrome'
      USE_CHROME_STABLE: 'true'
      NODE_ENV: 'production'
      MAX_CONCURRENT_SESSIONS: 1
      DEFAULT_USER_DATA_DIR: /usr/src/app/user-data-dir
```

**app.js**
```js
// ...
    const authStrategy = new LocalAuth({
        clientId: 'master',
    });

    account = new Client({
        puppeteer: {
            headless: false,
            args: ['--no-sandbox'],
            browserWSEndpoint: process.env.BROWSER_URL,
        },
        qrMaxRetries: 10,
        disableMessageHistory: true,
        authStrategy,
    });

    account.initialize();
// ...
```

**Comment by eslambasher** [comment]
@MarStefo thanks for your answer, but when i try it the qr code not show up, i checked the directory .web_js_auth/session-master inside the container and it's empty, do u know why ?

**Comment by pauloboc** [comment]
@eslambasher In my case it was a write permission problem.

**Comment by MarStefo** [comment]
Yes, I actually had the same permissions problem. I found this out via an "ls" of the shared folder in the browserless container.
Solved with the good old "chmod -R 777" but gladly listen to better proposals 😄

**Comment by gg3083** [comment]
Can I have a look at your Dockerfile

**Comment by FantinRaimbault** [comment]
Hi, I struggled a lot to set up the project with docker and I want to share what I did.

**client.js**

```js
const qrcode = require('qrcode-terminal');
const { GroupChat } = require('whatsapp-web.js');
const { Client, LocalAuth } = require('whatsapp-web.js');

const client = new Client({
    authStrategy: new LocalAuth({
        dataPath: '../'
    }),
    puppeteer: {
        headless: false,
        args: ['--no-sandbox'],
        browserWSEndpoint: process.env.BROWSER_URL,
    },
});

client.on('qr', (qr) => {
    qrcode.generate(qr, {small: true});
});

client.on('ready', async () => {
    console.log('Client is ready!');

});

client.on('message', async (message) => {
   console.log(message)
})

client.initialize().catch(console.error);
```

**Dockerfile**

```yml
FROM  node:17.0.0-alpine

RUN apk add chromium

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

EXPOSE 3001
```

**docker-compose.yml**

```yml
version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/node
    ports:
      - 3001:3001
    volumes:
      - .:/home/node
    networks:
      - whats-app-bot
    environment:
      BROWSER_URL: 'ws://browser:3000'
    depends_on:
      - browser
      
  mongodb:
      image: mongo:4.2.1-bionic
      ports:
        - '27017:27017'
      volumes:
        - ./db-data-mongodb:/data/db
      networks:
        - whats-app-bot

  browser:
    image: browserless/chrome:latest
    hostname: browser
    volumes:
      - ./.wwebjs_auth/session/:/usr/src/app/user-data-dir
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: 'true'
      WORKSPACE_EXPIRE_DAYS: 1
      ENABLE_CORS: 'true'
      CHROME_REFRESH_TIME: 86400000
      DEFAULT_BLOCK_ADS: 'true'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      ENABLE_XVBF: 'true'
      CHROME_PATH: '/usr/bin/google-chrome'
      USE_CHROME_STABLE: 'true'
      NODE_ENV: 'production'
      MAX_CONCURRENT_SESSIONS: 1
      DEFAULT_USER_DATA_DIR: /usr/src/app/user-data-dir
    ports:
      - 3000:3000
    networks:
        - whats-app-bot


networks:
  whats-app-bot:
    driver: bridge
```

**My architecture's repo is like that (monorepo and use npm workspace)**

- > .wwebjs_auth/session/Default ...
- >whats-app-bot-events/index.js
- >docker-compose.yml
- > Dockerfile
- > package.json
