### ISSUE TITLE
How to setup docker volume, Since I am not able to restore session

### ISSUE THREAD

**Issue by theromie** [pedroslopez/whatsapp-web.js#2627]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

I want to persist the session since I am using docker, I have created a volume directory for it .wweb_auth but no files or session is stored in the volume folder.

**docker-compose**
```
server:
    image: server
    ports:
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./volumes/log/server:/var/log/nodejs
      - ./volumes/wweb_auth:/usr/src/app/.wweb_auth
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9001/"]
      interval: 1m
      timeout: 10s
      retries: 3
```

**.env file:**
`WWEBJS_AUTH=./volumes/wweb_auth`

**NodeJs**
```
new Client({
    authStrategy: new LocalAuth({
      clientId: id,
      dataPath: path.join(`${__dirname}/${process.env.WWEBJS_AUTH}`),
    })
});
```

### Expected behavior

It should store data in a volume folder.

### Steps to Reproduce the Bug or Issue

Create a project on docker.

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS:  Linux, Docker + Ubuntu 18
Phone OS  iOS
whatsapp-web.js version: 1.23.0
Node.js Version: 18.15.0
WhatsApp Web version: 2.2350.1
