### ISSUE TITLE
Illegal Instruction (Core Dumped)

### ISSUE THREAD

**Issue by Ian-Kibet** [pedroslopez/whatsapp-web.js#983]
### Bug description
I have been trying to run on docker but i get the following error, on my laptop it works.

### Reproduction steps
1. `Docker build -t <image>` 
2. `Docker push <image>`
3. Deployed using `docker-compose`

### Expected behavior 
I should have gotten a QR code output in the terminal

### Relevant code
Docker-compose.yml
```
version: '3.3'

services:
  app:
    image: <image>
    ports:
      - 29331:29331
    environment:
      - REDIS_HOST=redis
      - SERVER_URL=localhost
      - SERVER_PORT=29331
      - BROWSERLESS=ws://browserless:9898/
    depends_on:
      - redis
      - browserless
    links:
      - browserless
    restart: unless-stopped

...

  browserless:
    image: browserless/chrome:latest
    ports: 
      - 9898:3000
    environment:
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - CHROME_REFRESH_TIME=86400000
      - MAX_CONCURRENT_SESSIONS=1
      - MAX_QUEUE_LENGTH=20
      - CONNECTION_TIMEOUT=-1
      - ENABLE_CORS=true
    restart: unless-stopped
```
Dockerfile
```
FROM node:16.10.0

ENV SERVER_URL localhost
ENV SERVER_PORT 29331

RUN mkdir /home/node/app

WORKDIR /home/node/app

RUN chown -R node:node .

USER node

COPY package*.json ./

RUN npm ci --only=production

COPY . .

CMD npm run start

```
### Environment (please complete the following information):
**WhatsApp**
 - Account type: Business
 - Device OS: Android

**Library**
 - Browser [Chrome / Chromium]: Browserless(Chromium)
 - NodeJS version: v16.11.0
 - npm or yarn version: 8.0.0
 - whatsapp-web.js version: ^1.15.1

**Other**
 - Operating system (the one running node) [Linux / MacOS / Windows]: Linux
 - Operating system version (ex. Windows 10):  Debian 10 Stretch
